[package]
name = "umadb-server"
description = "Event store Dynamic Consistency Boundaries"
repository = "https://github.com/umadb-io/umadb"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
umadb-dcb = { path = "../umadb-dcb", version = "0.1.22" }
umadb-core = { path = "../umadb-core", version = "0.1.22" }
umadb-proto = { path = "../umadb-proto", version = "0.1.22" }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
futures = { workspace = true }
tokio-stream = "0.1.14"
async-trait = { workspace = true }
